---
kind: pipeline
name: workflow
steps:
  - name: fake-test
    image: ehco1996/aioshadowsocks:latest
    commands:
      - python tests/test.py
    when:
      branch:
        include:
          - feature/*
          - master
          - dev
      event:
        include:
          - push
          - pull_request

  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl delete pods -l app=ss -n shadowsocks