---
kind: pipeline
name: workflow
steps:
  - name: fake-test
    image: ehco1996/aioshadowsocks:latest
    commands:
      - python tests/test.py
    when:
      branch:
        include:
          - feature/*
          - master
          - dev
      event:
        include:
          - push
          - pull_request