---
kind: pipeline
name: workflow
steps:
  - name: fake-test
    image: ehco1996/aioshadowsocks:latest
    commands:
      - python tests/test.py
    when:
      branch:
        include:
          - feature/*
          - master
          - dev
      event:
        include:
          - push
          - pull_request

  - name: build-image
    image: plugins/docker
    settings:
      repo: ehco1996/aioshadowsocks
      username: ehco1996
      password:
        from_secret: DOCKER_PASSWORD
      auto_tag: true