version: '3'

services:
  ss:
    container_name : aioshadowsocks
    # build: .
    image: ehco1996/aioshadowsocks:init
    network_mode: host
    restart: always
    environment:
      AIO_SS_API_ENDPOINT: ""
      AIO_SS_LOG_LEVEL: "info"
      AIO_SS_SYNC_TIME: 60
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
    volumes:
      - .:/src/aioshadowsocks
    working_dir: /src/aioshadowsocks
    command: python server.py
