version: '3'

services:
  ss:
    container_name : aioshadowsocks
    # build: .
    image: ehco1996/aioshadowsocks:init
    network_mode: host
    restart: always
    environment:
      API_ENDPOINT: ""
      LOG_LEVEL: "info"
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
    volumes:
      - .:/src/aioshadowsocks
    working_dir: /src/aioshadowsocks
    command: python server.py
