version: '3'

services:
  ss:
    container_name : aioshadowsocks
    image: ehco1996/aioshadowsocks:latest
    network_mode: host
    restart: always
    environment:
      SS_API_ENDPOINT: ""
      SS_LOG_LEVEL: "info"
      SS_SYNC_TIME: 60
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
    volumes:
      - .:/src/aioshadowsocks
    working_dir: /src/aioshadowsocks
    command: python server.py
